### ISSUE TITLE
Broken Google Drive Link for Model Download

### ISSUE THREAD

**Issue by hardtoname0907** [ananthu-aniraj/masking_strategies_bias_removal#1]
Thank you for your outstanding work and for making it open-source. It's an honor to learn from it. However, I noticed that the Google Drive link provided in the "models" part for "The segmentation model that we used for early and late masking can be downloaded from here" seems to be broken. Could you please update the link? I would like to reproduce your test results. Thank you.

**Comment by ananthu-aniraj** [comment]
Thanks for raising the issue. 

I've now updated the download link for the model
